// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeEzFDt1hzzyJ1ZP9ci6ov2oi6RLpy6O4',
    appId: '1:459894940156:web:91c6dcb1ad0696ddbb9279',
    messagingSenderId: '459894940156',
    projectId: 'fluttermessenger-fa674',
    authDomain: 'fluttermessenger-fa674.firebaseapp.com',
    storageBucket: 'fluttermessenger-fa674.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtoqXMeGfS1Gu0wkufWXa8tTc2vxoExI4',
    appId: '1:459894940156:android:e7e9530c3abe98d1bb9279',
    messagingSenderId: '459894940156',
    projectId: 'fluttermessenger-fa674',
    storageBucket: 'fluttermessenger-fa674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxyt3iHZlJRIPgH1Zq04AprN22AMboHg0',
    appId: '1:459894940156:ios:3cad23578e017772bb9279',
    messagingSenderId: '459894940156',
    projectId: 'fluttermessenger-fa674',
    storageBucket: 'fluttermessenger-fa674.appspot.com',
    iosClientId: '459894940156-9ub841vr1obaoodaan0oip7culra2c3i.apps.googleusercontent.com',
    iosBundleId: 'com.fluttermessanger.flutterMessanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxyt3iHZlJRIPgH1Zq04AprN22AMboHg0',
    appId: '1:459894940156:ios:3cad23578e017772bb9279',
    messagingSenderId: '459894940156',
    projectId: 'fluttermessenger-fa674',
    storageBucket: 'fluttermessenger-fa674.appspot.com',
    iosClientId: '459894940156-9ub841vr1obaoodaan0oip7culra2c3i.apps.googleusercontent.com',
    iosBundleId: 'com.fluttermessanger.flutterMessanger',
  );
}
